#!/usr/bin/env python
from __future__ import print_function
from sys import stdin, stderr

if __name__ == "__main__":

    sum = 0
    for line in stdin:
        line = line.strip()
        if line is not '' and line.isdigit():
            sum += int(line)
        else:
            stderr.write("Non-numeric line detected [accumulate]: " + line + "\n") 
    print(sum)
