#!/usr/bin/env python
from sys import stdin, argv

if __name__ == "__main__":

    if len(argv) > 1:
        with open(argv[1], "r") as ifi:
            for line in ifi:
                tokens = line.strip().split("\t")
                print("-".join([":".join([tokens[0], tokens[1]]), tokens[2]]))
    else:
        for line in stdin:
            tokens = line.strip().split("\t")
            print("-".join([":".join([tokens[0], tokens[1]]), tokens[2]]))
