#!/usr/bin/env python
from sys import stdin, argv

if __name__ == "__main__":

    if len(argv) > 1:
        with open(argv[1], "r") as ifi:
            for line in ifi:
                with open(line.strip(), "r") as i:
                    for line in i:
                        print(line.strip())
    else:
        for line in stdin:
            with open(line.strip(), "r") as i:
                for line in i:
                    print(line.strip())
