#!/usr/bin/env python
import sys
from collections import defaultdict
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--count", help="Output counts of distinct input lines.", required=False, default=False, dest="count", action="store_true")
    
    return parser.parse_args()


if __name__ == "__main__":

    args = parse_args()
    
    d = defaultdict(int)
    for line in sys.stdin:
        d[line.strip()] += 1

    if args.count:
        for i in d:
            print ("\t".join([ " ", str(d[i]), str(i)]))
    else:
        for i in d:
            print (str(i))

