#!/usr/bin/env python
import urllib.request
import argparse
import http.server
import socketserver


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-P", "--port", type=int, help="Open the file server on a specific port (default: 8080)", default=8080)
    return parser.parse_args()

if __name__ == "__main__":
    args = parse_args()
    external_ip = urllib.request.urlopen('https://v4.ident.me').read().decode('utf8')

    handler = http.server.SimpleHTTPRequestHandler

    with socketserver.TCPServer(("", args.port), handler) as httpd:
        print("Server started on localhost:" +  str(args.port))
        #print("Internal IP: " + external_ip + ":" + str(args.port))
        print("External IP: " + external_ip + ":" + str(args.port))
        httpd.serve_forever()
