#!/usr/bin/env python
import urllib.request
import sys

url = sys.argv[1]
usock = urllib.request.urlopen(url)
size =  usock.info().get('Content-Length')
if size is None:
    size = 0
size = float(size) # in bytes
size = size / 1024.0 / 1024.0
size = round(size, 2)
if (size < 1000):
    print(size, "MB")
else:
    size = size / 1024.0 ## Kilo to mega to giga-bytes
    size = round(size, 2)
    print(size, "GB")
