#!/usr/bin/env python
import sys

if __name__ == "__main__":

    with open(sys.argv[1], "r") as ifi:
        for line in ifi:
            line = line.strip()
            if sys.argv[2] in line:
                line = line.replace(sys.argv[2], sys.argv[3])
            print(line)
