#!/usr/bin/env python
import sys

def usage():
    h = "subtract: take the difference of two integer columns\n"
    h += "Usage: cat <input> | subtract [<firstInt> <secondInt> <columnDelimiter>]"
    print(h)

if __name__ == "__main__":

    bigindex = 2
    littleindex = 1
    tokenizer = "\t"
    
    if len(sys.argv) == 3:
        bigindex = int(sys.argv[1])
        littleindex = int(sys.argv[2])


    if len(sys.argv) == 4:
        tokenizer = sys.argv[3]

    for line in sys.stdin:
        tokens = line.strip().split(tokenizer)
        val = int(tokens[bigindex]) - int(tokens[littleindex])
        print(val)

