#!/usr/bin/env python
import sys
import argparse

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", type=str, dest="fragment")

    return parser.parse_args()    

if __name__ == "__main__":

    args = parse_args()
    fragments = [int(i) for i in args.fragment.split(",")]
    for line in sys.stdin:
        tokens = line.strip().split()
        tokens = [value for i, value in enumerate(tokens) if i in fragments]
        ret = "\t".join(tokens)
        print(ret)

