#!/bin/bash
# Faster, but can't handle streams
# Courtesy of Aaron Quinalan (and others)
# Source available at https://gist.github.com/arq5x/ab78b7be4d4f2a989a31

[ $# -eq 0 ] && { echo "Sorts a VCF file in natural chromosome order";\
    echo "Usage: $0 [my.vcf | my.vcf.gz]"; exit 1;
}
# cheers, @michaelhoffman
if (zless $1 | grep ^#; zless $1 | grep -v ^# | LC_ALL=C sort -k1,1V -k2,2n);
then
    exit 0
else
    printf 'sort failed. Does your version of sort support the -V option?\n'
    printf 'If not, you should update sort with the latest from GNU coreutils:\n'
    printf 'git clone git://git.sv.gnu.org/coreutils'
fi
